name: "Bug Report"
description: "Report a bug you found"
title: "[Bug]: "
labels: ["bug"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues
          required: true

  - type: markdown
    attributes:
      value: "Please give info on the bug you encountered:"
      
  - type: input
    id: summary
    attributes:
      label: "Bug Summary"
      description: "Provide a brief description of the bug."
      placeholder: "Short summary of the bug"
    validations:
      required: true

  - type: textarea
    id: stepsToReproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Describe the steps taken to encounter this bug."
      placeholder: "1. Go to...\n2. Click on...\n3. Observe..."
    validations:
      required: true
      
  - type: textarea
    id: explanation
    attributes:
      label: "Detailed description of the bug"
      description: "Describe what went wrong"
      placeholder: "It just ain't workin'"
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Have you applied the correct lables?
      options:
        - label: I applied the correct lables
          required: true
