name: "Documentation Update"
description: "Propose an update to the documentation."
title: "[Docs Update]: "
labels: ["documentation"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    id: document-section
    attributes:
      label: "Document Section"
      description: "Specify the document or section to update."
      placeholder: "update Documentation.txt"
    validations:
      required: true

  - type: textarea
    id: update-details
    attributes:
      label: "Update Details"
      description: "Describe the changes needed in the documentation."
    validations:
      required: true
  
- type: checkboxes
    attributes:
      label: Have you applied the correct lables?
      options:
        - label: I applied the correct lables
          required: true
