package progi.config;

import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import progi.data.City;
import progi.repositories.CityRepository;

@Configuration
public class CityConfig {
    @Bean
    CommandLineRunner cityCommandLineRunner(CityRepository cityRepository) {
        return args -> {
            cityRepository.saveAll(
                    List.of(
                            new City("Andrijaševci"),
                            new City("Antunovac"),
                            new City("Babina Greda"),
                            new City("Bakar"),
                            new City("Bale"),
                            new City("Barban"),
                            new City("Barilović"),
                            new City("Baška"),
                            new City("Baška Voda"),
                            new City("Bebrina"),
                            new City("Bedekovčina"),
                            new City("Bedenica"),
                            new City("Bednja"),
                            new City("Beli Manastir"),
                            new City("Belica"),
                            new City("Belišće"),
                            new City("Benkovac"),
                            new City("Berek"),
                            new City("Beretinec"),
                            new City("Bibinje"),
                            new City("Bilice"),
                            new City("Bilje"),
                            new City("Biograd na Moru"),
                            new City("Biskupija"),
                            new City("Bistra"),
                            new City("Bizovac"),
                            new City("Bjelovar"),
                            new City("Blato"),
                            new City("Bogdanovci"),
                            new City("Bol"),
                            new City("Borovo"),
                            new City("Bosiljevo"),
                            new City("Bošnjaci"),
                            new City("Brckovljani"),
                            new City("Brdovec"),
                            new City("Brela"),
                            new City("Brestovac"),
                            new City("Breznica"),
                            new City("Breznički Hum"),
                            new City("Brinje"),
                            new City("Brod Moravice"),
                            new City("Brodski Stupnik"),
                            new City("Brtonigla"),
                            new City("Budinščina"),
                            new City("Buje"),
                            new City("Bukovlje"),
                            new City("Buzet"),
                            new City("Cerna"),
                            new City("Cernik"),
                            new City("Cerovlje"),
                            new City("Cestica"),
                            new City("Cetingrad"),
                            new City("Cista Provo"),
                            new City("Civljane"),
                            new City("Cres"),
                            new City("Crikvenica"),
                            new City("Crnac"),
                            new City("Čabar"),
                            new City("Čačinci"),
                            new City("Čađavica"),
                            new City("Čaglin"),
                            new City("Čakovec"),
                            new City("Čavle"),
                            new City("Čazma"),
                            new City("Čeminac"),
                            new City("Čepin"),
                            new City("Darda"),
                            new City("Daruvar"),
                            new City("Davor"),
                            new City("Dekanovec"),
                            new City("Delnice"),
                            new City("Desinić"),
                            new City("Dežanovac"),
                            new City("Dicmo"),
                            new City("Dobrinj"),
                            new City("Domašinec"),
                            new City("Donja Dubrava"),
                            new City("Donja Motičina"),
                            new City("Donja Stubica"),
                            new City("Donja Voća"),
                            new City("Donji Andrijevci"),
                            new City("Donji Kraljevec"),
                            new City("Donji Kukuruzari"),
                            new City("Donji Lapac"),
                            new City("Donji Miholjac"),
                            new City("Donji Vidovec"),
                            new City("Dragalić"),
                            new City("Draganić"),
                            new City("Draž"),
                            new City("Drenovci"),
                            new City("Drenje"),
                            new City("Drniš"),
                            new City("Drnje"),
                            new City("Dubrava"),
                            new City("Dubravica"),
                            new City("Dubrovačko primorje"),
                            new City("Dubrovnik"),
                            new City("Duga Resa"),
                            new City("Dugi Rat"),
                            new City("Dugo Selo"),
                            new City("Dugopolje"),
                            new City("Dvor"),
                            new City("Đakovo"),
                            new City("Đelekovec"),
                            new City("Đulovac"),
                            new City("Đurđenovac"),
                            new City("Đurđevac"),
                            new City("Đurmanec"),
                            new City("Erdut"),
                            new City("Ernestinovo"),
                            new City("Ervenik"),
                            new City("Farkaševac"),
                            new City("Fažana"),
                            new City("Ferdinandovac"),
                            new City("Feričanci"),
                            new City("Funtana-Fontane"),
                            new City("Fužine"),
                            new City("Galovac"),
                            new City("Garčin"),
                            new City("Garešnica"),
                            new City("Generalski Stol"),
                            new City("Glina"),
                            new City("Gola"),
                            new City("Goričan"),
                            new City("Gorjani"),
                            new City("Gornja Rijeka"),
                            new City("Gornja Stubica"),
                            new City("Gornja Vrba"),
                            new City("Gornji Bogićevci"),
                            new City("Gornji Kneginec"),
                            new City("Gornji Mihaljevec"),
                            new City("Gospić"),
                            new City("Gračac"),
                            new City("Gračišće"),
                            new City("Grad Zagreb"),
                            new City("Gradac"),
                            new City("Gradec"),
                            new City("Gradina"),
                            new City("Gradište"),
                            new City("Grožnjan"),
                            new City("Grubišno Polje"),
                            new City("Gundinci"),
                            new City("Gunja"),
                            new City("Gvozd"),
                            new City("Hercegovac"),
                            new City("Hlebine"),
                            new City("Hrašćina"),
                            new City("Hrvace"),
                            new City("Hrvatska Dubica"),
                            new City("Hrvatska Kostajnica"),
                            new City("Hum na Sutli"),
                            new City("Hvar"),
                            new City("Ilok"),
                            new City("Imotski"),
                            new City("Ivanec"),
                            new City("Ivanić-Grad"),
                            new City("Ivankovo"),
                            new City("Ivanska"),
                            new City("Jagodnjak"),
                            new City("Jakovlje"),
                            new City("Jakšić"),
                            new City("Jalžabet"),
                            new City("Janjina"),
                            new City("Jarmina"),
                            new City("Jasenice"),
                            new City("Jasenovac"),
                            new City("Jastrebarsko"),
                            new City("Jelenje"),
                            new City("Jelsa"),
                            new City("Jesenje"),
                            new City("Josipdol"),
                            new City("Kali"),
                            new City("Kalinovac"),
                            new City("Kalnik"),
                            new City("Kamanje"),
                            new City("Kanfanar"),
                            new City("Kapela"),
                            new City("Kaptol"),
                            new City("Karlobag"),
                            new City("Karlovac"),
                            new City("Karojba"),
                            new City("Kastav"),
                            new City("Kaštela"),
                            new City("Kaštelir-Labinci"),
                            new City("Kijevo"),
                            new City("Kistanje"),
                            new City("Klakar"),
                            new City("Klana"),
                            new City("Klanjec"),
                            new City("Klenovnik"),
                            new City("Klinča Sela"),
                            new City("Klis"),
                            new City("Kloštar Ivanić"),
                            new City("Kloštar Podravski"),
                            new City("Kneževi Vinogradi"),
                            new City("Knin"),
                            new City("Kolan"),
                            new City("Komiža"),
                            new City("Konavle"),
                            new City("Končanica"),
                            new City("Konjščina"),
                            new City("Koprivnica"),
                            new City("Koprivnički Bregi"),
                            new City("Koprivnički Ivanec"),
                            new City("Korčula"),
                            new City("Kostrena"),
                            new City("Koška"),
                            new City("Kotoriba"),
                            new City("Kraljevec na Sutli"),
                            new City("Kraljevica"),
                            new City("Krapina"),
                            new City("Krapinske Toplice"),
                            new City("Krašić"),
                            new City("Kravarsko"),
                            new City("Križ"),
                            new City("Križevci"),
                            new City("Krk"),
                            new City("Krnjak"),
                            new City("Kršan"),
                            new City("Kukljica"),
                            new City("Kula Norinska"),
                            new City("Kumrovec"),
                            new City("Kutina"),
                            new City("Kutjevo"),
                            new City("Labin"),
                            new City("Lanišće"),
                            new City("Lasinja"),
                            new City("Lastovo"),
                            new City("Lećevica"),
                            new City("Legrad"),
                            new City("Lekenik"),
                            new City("Lepoglava"),
                            new City("Levanjska Varoš"),
                            new City("Lipik"),
                            new City("Lipovljani"),
                            new City("Lišane Ostrovičke"),
                            new City("Ližnjan"),
                            new City("Lobor"),
                            new City("Lokve"),
                            new City("Lokvičići"),
                            new City("Lopar"),
                            new City("Lovas"),
                            new City("Lovinac"),
                            new City("Lovran"),
                            new City("Lovreć"),
                            new City("Ludbreg"),
                            new City("Luka"),
                            new City("Lukač"),
                            new City("Lumbarda"),
                            new City("Lupoglav"),
                            new City("Ljubešćica"),
                            new City("Mače"),
                            new City("Magadenovac"),
                            new City("Majur"),
                            new City("Makarska"),
                            new City("Mala Subotica"),
                            new City("Mali Bukovec"),
                            new City("Mali Lošinj"),
                            new City("Malinska-Dubašnica"),
                            new City("Marčana"),
                            new City("Marija Bistrica"),
                            new City("Marija Gorica"),
                            new City("Marijanci"),
                            new City("Marina"),
                            new City("Markušica"),
                            new City("Martijanec"),
                            new City("Martinska Ves"),
                            new City("Maruševec"),
                            new City("Matulji"),
                            new City("Medulin"),
                            new City("Metković"),
                            new City("Mihovljan"),
                            new City("Mikleuš"),
                            new City("Milna"),
                            new City("Mljet"),
                            new City("Molve"),
                            new City("Mošćenička Draga"),
                            new City("Motovun"),
                            new City("Mrkopalj"),
                            new City("Muć"),
                            new City("Mursko Središće"),
                            new City("Murter"),
                            new City("Našice"),
                            new City("Nedelišće"),
                            new City("Negoslavci"),
                            new City("Nerežišća"),
                            new City("Netretić"),
                            new City("Nijemci"),
                            new City("Nin"),
                            new City("Nova Bukovica"),
                            new City("Nova Gradiška"),
                            new City("Nova Kapela"),
                            new City("Nova Rača"),
                            new City("Novalja"),
                            new City("Novi Golubovec"),
                            new City("Novi Marof"),
                            new City("Novi Vinodolski"),
                            new City("Novigrad (Istarska)"),
                            new City("Novigrad (Zadarska)"),
                            new City("Novigrad Podravski"),
                            new City("Novo Virje"),
                            new City("Novska"),
                            new City("Nuštar"),
                            new City("Obrovac"),
                            new City("Ogulin"),
                            new City("Okrug"),
                            new City("Okučani"),
                            new City("Omiš"),
                            new City("Omišalj"),
                            new City("Opatija"),
                            new City("Oprisavci"),
                            new City("Oprtalj"),
                            new City("Opuzen"),
                            new City("Orahovica"),
                            new City("Orebić"),
                            new City("Orehovica"),
                            new City("Oriovac"),
                            new City("Orle"),
                            new City("Oroslavje"),
                            new City("Osijek"),
                            new City("Otočac"),
                            new City("Otok (Splitsko-dalmatinska)"),
                            new City("Otok (Vukovarsko-srijemska)"),
                            new City("Ozalj"),
                            new City("Pag"),
                            new City("Pakoštane"),
                            new City("Pakrac"),
                            new City("Pašman"),
                            new City("Pazin"),
                            new City("Perušić"),
                            new City("Peteranec"),
                            new City("Petlovac"),
                            new City("Petrijanec"),
                            new City("Petrijevci"),
                            new City("Petrinja"),
                            new City("Petrovsko"),
                            new City("Pićan"),
                            new City("Pirovac"),
                            new City("Pisarovina"),
                            new City("Pitomača"),
                            new City("Plaški"),
                            new City("Pleternica"),
                            new City("Plitvička Jezera"),
                            new City("Ploče"),
                            new City("Podbablje"),
                            new City("Podcrkavlje"),
                            new City("Podgora"),
                            new City("Podgorač"),
                            new City("Podravska Moslavina"),
                            new City("Podravske Sesvete"),
                            new City("Podstrana"),
                            new City("Podturen"),
                            new City("Pojezerje"),
                            new City("Pokupsko"),
                            new City("Polača"),
                            new City("Poličnik"),
                            new City("Popovac"),
                            new City("Popovača"),
                            new City("Poreč"),
                            new City("Posedarje"),
                            new City("Postira"),
                            new City("Povljana"),
                            new City("Požega"),
                            new City("Pregrada"),
                            new City("Preko"),
                            new City("Prelog"),
                            new City("Preseka"),
                            new City("Prgomet"),
                            new City("Pribislavec"),
                            new City("Primorski Dolac"),
                            new City("Primošten"),
                            new City("Privlaka (Zadarska)"),
                            new City("Privlaka (Vukovarsko-srijemsa)"),
                            new City("Proložac"),
                            new City("Promina"),
                            new City("Pučišća"),
                            new City("Pula"),
                            new City("Punat"),
                            new City("Punitovci"),
                            new City("Pušća"),
                            new City("Rab"),
                            new City("Radoboj"),
                            new City("Rakovec"),
                            new City("Rakovica"),
                            new City("Rasinja"),
                            new City("Raša"),
                            new City("Ravna Gora"),
                            new City("Ražanac"),
                            new City("Rešetari"),
                            new City("Ribnik"),
                            new City("Rijeka"),
                            new City("Rogoznica"),
                            new City("Rovinj"),
                            new City("Rovišće"),
                            new City("Rugvica"),
                            new City("Runovići"),
                            new City("Ružić"),
                            new City("Saborsko"),
                            new City("Sali"),
                            new City("Samobor"),
                            new City("Satnica Đakovačka"),
                            new City("Seget"),
                            new City("Selca"),
                            new City("Selnica"),
                            new City("Semeljci"),
                            new City("Senj"),
                            new City("Severin"),
                            new City("Sibinj"),
                            new City("Sikirevci"),
                            new City("Sinj"),
                            new City("Sirač"),
                            new City("Sisak"),
                            new City("Skrad"),
                            new City("Skradin"),
                            new City("Slatina"),
                            new City("Slavonski Brod"),
                            new City("Slavonski Šamac"),
                            new City("Slivno"),
                            new City("Slunj"),
                            new City("Smokvica"),
                            new City("Sokolovac"),
                            new City("Solin"),
                            new City("Sopje"),
                            new City("Split"),
                            new City("Sračinec"),
                            new City("Stankovci"),
                            new City("Stara Gradiška"),
                            new City("Stari Grad"),
                            new City("Stari Jankovci"),
                            new City("Stari Mikanovci"),
                            new City("Starigrad"),
                            new City("Staro Petrovo Selo"),
                            new City("Ston"),
                            new City("Strahoninec"),
                            new City("Strizivojna"),
                            new City("Stubičke Toplice"),
                            new City("Stupnik"),
                            new City("Sućuraj"),
                            new City("Suhopolje"),
                            new City("Sukošan"),
                            new City("Sunja"),
                            new City("Supetar"),
                            new City("Sutivan"),
                            new City("Sveta Marija"),
                            new City("Sveta Nedelja (Istarska)"),
                            new City("Sveta Nedjelja (Zagrebačka)"),
                            new City("Sveti Đurđ"),
                            new City("Sveti Filip i Jakov"),
                            new City("Sveti Ilija"),
                            new City("Sveti Ivan Zelina"),
                            new City("Sveti Ivan Žabno"),
                            new City("Sveti Juraj na Bregu"),
                            new City("Sveti Križ Začretje"),
                            new City("Sveti Lovreč"),
                            new City("Sveti Martin na Muri"),
                            new City("Sveti Petar Orehovec"),
                            new City("Sveti Petar u Šumi"),
                            new City("Svetvinčenat"),
                            new City("Šandrovac"),
                            new City("Šenkovec"),
                            new City("Šestanovac"),
                            new City("Šibenik"),
                            new City("Škabrnja"),
                            new City("Šodolovci"),
                            new City("Šolta"),
                            new City("Špišić Bukovica"),
                            new City("Štefanje"),
                            new City("Štitar"),
                            new City("Štrigova"),
                            new City("Tar-Vabriga"),
                            new City("Tinjan"),
                            new City("Tisno"),
                            new City("Tkon"),
                            new City("Tompojevci"),
                            new City("Topusko"),
                            new City("Tordinci"),
                            new City("Tounj"),
                            new City("Tovarnik"),
                            new City("Tribunj"),
                            new City("Trilj"),
                            new City("Trnava"),
                            new City("Trnovec Bartolovečki"),
                            new City("Trogir"),
                            new City("Trpanj"),
                            new City("Trpinja"),
                            new City("Tučepi"),
                            new City("Tuhelj"),
                            new City("Udbina"),
                            new City("Umag"),
                            new City("Unešić"),
                            new City("Valpovo"),
                            new City("Varaždin"),
                            new City("Varaždinske Toplice"),
                            new City("Vela Luka"),
                            new City("Velika"),
                            new City("Velika Gorica"),
                            new City("Velika Kopanica"),
                            new City("Velika Ludina"),
                            new City("Velika Pisanica"),
                            new City("Velika Trnovitica"),
                            new City("Veliki Bukovec"),
                            new City("Veliki Grđevac"),
                            new City("Veliko Trgovišće"),
                            new City("Veliko Trojstvo"),
                            new City("Vidovec"),
                            new City("Viljevo"),
                            new City("Vinica"),
                            new City("Vinkovci"),
                            new City("Vinodolska općina"),
                            new City("Vir"),
                            new City("Virje"),
                            new City("Virovitica"),
                            new City("Vis"),
                            new City("Visoko"),
                            new City("Viškovci"),
                            new City("Viškovo"),
                            new City("Višnjan"),
                            new City("Vižinada"),
                            new City("Vladislavci"),
                            new City("Voćin"),
                            new City("Vodice"),
                            new City("Vodnjan"),
                            new City("Vođinci"),
                            new City("Vojnić"),
                            new City("Vratišinec"),
                            new City("Vrbanja"),
                            new City("Vrbje"),
                            new City("Vrbnik"),
                            new City("Vrbovec"),
                            new City("Vrbovsko"),
                            new City("Vrgorac"),
                            new City("Vrhovine"),
                            new City("Vrlika"),
                            new City("Vrpolje"),
                            new City("Vrsar"),
                            new City("Vrsi"),
                            new City("Vuka"),
                            new City("Vukovar"),
                            new City("Zabok"),
                            new City("Zadar"),
                            new City("Zadvarje"),
                            new City("Zagorska Sela"),
                            new City("Zagvozd"),
                            new City("Zaprešić"),
                            new City("Zažablje"),
                            new City("Zdenci"),
                            new City("Zemunik Donji"),
                            new City("Zlatar"),
                            new City("Zlatar Bistrica"),
                            new City("Zmijavci"),
                            new City("Zrinski Topolovac"),
                            new City("Žakanje"),
                            new City("Žminj"),
                            new City("Žumberak"),
                            new City("Župa dubrovačka"),
                            new City("Županja")));
        };
    }
}
