name: Build and Push Backend Image

on:
  push:
    branches:
      - master
    paths:
      - "backend/**" # Trigger only on changes in the /backend directory
  workflow_dispatch:

jobs:
  build-and-push-backend:
    name: Build and Push Backend
    runs-on: ubuntu-latest
    env:
      BACKEND_DEPLOY_HOOK: ${{ secrets.BACKEND_DEPLOY_HOOK }}

    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env: 
          OWNER: '${{ github.repository_owner }}'
          
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/backend:latest"

      - name: Trigger release
        if: ${{ env.BACKEND_DEPLOY_HOOK }}
        run: curl ${{ env.BACKEND_DEPLOY_HOOK }}


      - name: Trigger release
        if: ${{ env.BACKEND_DEPLOY_HOOK }}
        run: curl ${{ env.BACKEND_DEPLOY_HOOK }}
